[dependency-groups]
dev = [
    "click==8.3.1",
    "pytest==9.0.2",
    "pytest-asyncio==1.3.0",
    "ruff==0.14.8",
    "watchfiles==1.1.1",
    "keycloakauthenticator @ file:///${PROJECT_ROOT}/KeyCloakAuthenticator",
    "swanculler @ file:///${PROJECT_ROOT}/SwanCuller",
    "swanhub @ file:///${PROJECT_ROOT}/SwanHub",
    "swannotificationsservice @ file:///${PROJECT_ROOT}/SwanNotificationsService",
    "swanspawner @ file:///${PROJECT_ROOT}/SwanSpawner",
]

[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
select = [
    "F401",
    "F541",
    "F811",
    "F841",
    "SIM118",
]
